BU:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: m2
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
  s_layers: 1
Bi:
  a: sca
  a_dim: 768
  a_ffdim: 768
  a_layers: 6
  a_nhead: 8
  dropout: 0.0
  f: LSTM
  f_dim: 768
  f_layers: 10
  f_ln: false
  f_ngp: 1
  hid_dim: 768
Bu:
  a: sa
  a_dim: null
  a_ffdim: null
  a_layers: 1
  a_nhead: 8
  dropout: null
  f: m2
  f_dim: null
  f_layers: 10
  f_ln: null
  f_ngp: null
  hid_dim: null
B2Q_Net:
  block: iUU
  cmr: 0.2
  fpos: false
  ntoken: 60
  mtoken: 30
  Nw: 16
  trans: false
  mwt: 0.0
Loss:
  p2fc: 1.0
  bgw: 1.0
  match: o2o
  nullw: -1.0
  pc: 0.3
  sw: 5.0
TM:
  inplace: true
  m: 5
  p: 0.05
  t: 30
  use: true
aux:
  debug: false
  eval_every: 2000
  gpu: 0
  mark: ""
  print_every: 1000
  resume: max
  runid: 0
  logdir: ./log/m2cai16/
  exp: exp1
clip_grad_norm: 10.0
dataset: m2cai16
momentum: 0.0
split: split1
sr: 1
weight_decay: 0.0
average_transcript_len: 6.8
bg_class: [0] 
nclasses: 8
